### PR TITLE
proposing corrections for week01 seminar

### PR DESCRIPTION
**Pull request by lopezjuanma96**
Just finished the week01 of the blog course. This is awesome! I'm learning a lot - although I have to say I'm skipping most of the complex formulas, not my string point -. 
In any case, found a few modifications that I feel could be of use. Hope they are of help, I'll continue with the week02 these next days.

- size is now vector_size in Word2Vec
- added print for model save path on gensim's api.load
- corrected PCA's bold initials, since asteriks seem to be best practice and some viewers don't work with underscores

### CODE REVIEW

**Comment by justheuristic** [comment]
Hi! Sorry for the late response. The week1 changes are perfect, but some of the changes you propose to week3  include solutions, e.g.

image

Our format requires that these notebooks are handout assignments that do not include solutions.

If you modify the code to exclude your solution, i'd be happy to merge this PR

**Comment by lopezjuanma96** [comment]
Oh that's bad, it seems the commit for my solutions got mixed up in the
pull request.. Is there any way you can use the corrections for week01? If
not I'll try to make them on a separate branch.

Btw, now that I am about a half into the course I have to tell you it is
amazing what you've done. I'm thinking of applying to the online courses at
Yandex at some point.

Thank you for your response, hope we can be in touch.

Juanma

**Comment by poedator** [comment]
Hi, @lopezjuanma96 
to save your work locally you may want to create a new branch from the latest commit here.
Then reset your 2022 branch to your original commit `a27bfac` and summon @justheuristic.

For additional contributions please use branch 2023

note to ourselves: pick this PR result into 2023 branch.

**Comment by lopezjuanma96** [comment]
I had a separate branch for solutions but it would seem i messed up and push some commits with solutions on main branch.

Okey, I'll try my best to do so, I can't promise I'll be successful in my first try, but I'll tell you when I'm done and we can recheck.

**Comment by poedator** [comment]
replaced with #151

**Pull request closed without merging**
